// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FormLoginPassword form login password
//
// swagger:model FormLoginPassword
type FormLoginPassword struct {

	// login
	Login string `json:"Login,omitempty"`

	// password
	Password string `json:"Password,omitempty"`
}

// Validate validates this form login password
func (m *FormLoginPassword) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this form login password based on context it is used
func (m *FormLoginPassword) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FormLoginPassword) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FormLoginPassword) UnmarshalBinary(b []byte) error {
	var res FormLoginPassword
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
