// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LuckModel luck model
//
// swagger:model LuckModel
type LuckModel struct {

	// luck number
	LuckNumber *LuckNumberModel `json:"luckNumber,omitempty"`
}

// Validate validates this luck model
func (m *LuckModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLuckNumber(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LuckModel) validateLuckNumber(formats strfmt.Registry) error {
	if swag.IsZero(m.LuckNumber) { // not required
		return nil
	}

	if m.LuckNumber != nil {
		if err := m.LuckNumber.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("luckNumber")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this luck model based on the context it is used
func (m *LuckModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLuckNumber(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LuckModel) contextValidateLuckNumber(ctx context.Context, formats strfmt.Registry) error {

	if m.LuckNumber != nil {
		if err := m.LuckNumber.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("luckNumber")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LuckModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LuckModel) UnmarshalBinary(b []byte) error {
	var res LuckModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
