// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LuckNumberModel luck number model
//
// swagger:model LuckNumberModel
type LuckNumberModel struct {

	// luck
	Luck float32 `json:"luck,omitempty"`

	// orphan rate
	OrphanRate float64 `json:"orphanRate,omitempty"`
}

// Validate validates this luck number model
func (m *LuckNumberModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this luck number model based on context it is used
func (m *LuckNumberModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LuckNumberModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LuckNumberModel) UnmarshalBinary(b []byte) error {
	var res LuckNumberModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
