// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MinerModel miner model
//
// swagger:model MinerModel
type MinerModel struct {

	// miner Uid
	MinerUID *MinerUIDModel `json:"minerUid,omitempty"`
}

// Validate validates this miner model
func (m *MinerModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMinerUID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MinerModel) validateMinerUID(formats strfmt.Registry) error {
	if swag.IsZero(m.MinerUID) { // not required
		return nil
	}

	if m.MinerUID != nil {
		if err := m.MinerUID.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("minerUid")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this miner model based on the context it is used
func (m *MinerModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMinerUID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MinerModel) contextValidateMinerUID(ctx context.Context, formats strfmt.Registry) error {

	if m.MinerUID != nil {
		if err := m.MinerUID.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("minerUid")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MinerModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MinerModel) UnmarshalBinary(b []byte) error {
	var res MinerModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
