// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MinerUIDModel miner Uid model
//
// swagger:model MinerUidModel
type MinerUIDModel struct {

	// height
	Height int64 `json:"height,omitempty"`

	// last beat
	LastBeat int64 `json:"lastBeat,omitempty"`

	// offline
	Offline *bool `json:"offline,omitempty"`
}

// Validate validates this miner Uid model
func (m *MinerUIDModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this miner Uid model based on context it is used
func (m *MinerUIDModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MinerUIDModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MinerUIDModel) UnmarshalBinary(b []byte) error {
	var res MinerUIDModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
