// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MinerReturnModel miner return model
//
// swagger:model MinerReturnModel
type MinerReturnModel struct {

	// hashrate
	Hashrate float32 `json:"hashrate,omitempty"`

	// miners
	Miners *MinerModel `json:"miners,omitempty"`

	// miners total
	MinersTotal int64 `json:"minersTotal,omitempty"`

	// now
	Now int64 `json:"now,omitempty"`
}

// Validate validates this miner return model
func (m *MinerReturnModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMiners(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MinerReturnModel) validateMiners(formats strfmt.Registry) error {
	if swag.IsZero(m.Miners) { // not required
		return nil
	}

	if m.Miners != nil {
		if err := m.Miners.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("miners")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this miner return model based on the context it is used
func (m *MinerReturnModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMiners(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MinerReturnModel) contextValidateMiners(ctx context.Context, formats strfmt.Registry) error {

	if m.Miners != nil {
		if err := m.Miners.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("miners")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MinerReturnModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MinerReturnModel) UnmarshalBinary(b []byte) error {
	var res MinerReturnModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
