// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NodeModel node model
//
// swagger:model NodeModel
type NodeModel struct {

	// avg block time
	AvgBlockTime string `json:"avgBlockTime,omitempty"`

	// difficulty
	Difficulty string `json:"difficulty,omitempty"`

	// height
	Height string `json:"height,omitempty"`

	// last beat
	LastBeat string `json:"lastBeat,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// networkhashps
	Networkhashps string `json:"networkhashps,omitempty"`
}

// Validate validates this node model
func (m *NodeModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this node model based on context it is used
func (m *NodeModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NodeModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NodeModel) UnmarshalBinary(b []byte) error {
	var res NodeModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
