// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PaymentsModel payments model
//
// swagger:model PaymentsModel
type PaymentsModel struct {

	// amount
	Amount int64 `json:"amount,omitempty"`

	// timestamp
	Timestamp int64 `json:"timestamp,omitempty"`

	// total payees
	TotalPayees int64 `json:"totalPayees,omitempty"`

	// tx
	Tx string `json:"tx,omitempty"`
}

// Validate validates this payments model
func (m *PaymentsModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this payments model based on context it is used
func (m *PaymentsModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaymentsModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaymentsModel) UnmarshalBinary(b []byte) error {
	var res PaymentsModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
