// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PaymentModel payment model
//
// swagger:model PaymentModel
type PaymentModel struct {

	// amount
	Amount int64 `json:"amount,omitempty"`

	// timestamp
	Timestamp int64 `json:"timestamp,omitempty"`

	// tx
	Tx string `json:"tx,omitempty"`
}

// Validate validates this payment model
func (m *PaymentModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this payment model based on context it is used
func (m *PaymentModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaymentModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaymentModel) UnmarshalBinary(b []byte) error {
	var res PaymentModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
