// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PoolChartsModel pool charts model
//
// swagger:model PoolChartsModel
type PoolChartsModel struct {

	// netdiff
	Netdiff float32 `json:"netdiff,omitempty"`

	// nethr
	Nethr float32 `json:"nethr,omitempty"`

	// time format
	TimeFormat string `json:"timeFormat,omitempty"`

	// x
	X int64 `json:"x,omitempty"`

	// y
	Y float32 `json:"y,omitempty"`
}

// Validate validates this pool charts model
func (m *PoolChartsModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pool charts model based on context it is used
func (m *PoolChartsModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PoolChartsModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PoolChartsModel) UnmarshalBinary(b []byte) error {
	var res PoolChartsModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
