// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RewardsModel rewards model
//
// swagger:model RewardsModel
type RewardsModel struct {

	// blockhash
	Blockhash string `json:"blockhash,omitempty"`

	// blockheight
	Blockheight int64 `json:"blockheight,omitempty"`

	// current luck
	CurrentLuck float32 `json:"currentLuck,omitempty"`

	// immature
	Immature *bool `json:"immature,omitempty"`

	// percent
	Percent float32 `json:"percent,omitempty"`

	// reward
	Reward int64 `json:"reward,omitempty"`

	// timestamp
	Timestamp int64 `json:"timestamp,omitempty"`

	// uncle
	Uncle *bool `json:"uncle,omitempty"`
}

// Validate validates this rewards model
func (m *RewardsModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rewards model based on context it is used
func (m *RewardsModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RewardsModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RewardsModel) UnmarshalBinary(b []byte) error {
	var res RewardsModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
