// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StatsModel stats model
//
// swagger:model StatsModel
type StatsModel struct {

	// balance
	Balance int64 `json:"balance,omitempty"`

	// blocks found
	BlocksFound int64 `json:"blocksFound,omitempty"`

	// immature
	Immature int64 `json:"immature,omitempty"`

	// last share
	LastShare int64 `json:"lastShare,omitempty"`

	// paid
	Paid int64 `json:"paid,omitempty"`

	// pending
	Pending int64 `json:"pending,omitempty"`
}

// Validate validates this stats model
func (m *StatsModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this stats model based on context it is used
func (m *StatsModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StatsModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StatsModel) UnmarshalBinary(b []byte) error {
	var res StatsModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
