// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SumrewardsModel sumrewards model
//
// swagger:model SumrewardsModel
type SumrewardsModel struct {

	// inverval
	Inverval int64 `json:"inverval,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// numreward
	Numreward int64 `json:"numreward,omitempty"`

	// offset
	Offset int64 `json:"offset,omitempty"`

	// reward
	Reward int64 `json:"reward,omitempty"`
}

// Validate validates this sumrewards model
func (m *SumrewardsModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sumrewards model based on context it is used
func (m *SumrewardsModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SumrewardsModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SumrewardsModel) UnmarshalBinary(b []byte) error {
	var res SumrewardsModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
