// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WorkerModel worker model
//
// swagger:model WorkerModel
type WorkerModel struct {

	// worker group
	WorkerGroup *WorkerGroupModel `json:"workerGroup,omitempty"`
}

// Validate validates this worker model
func (m *WorkerModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateWorkerGroup(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WorkerModel) validateWorkerGroup(formats strfmt.Registry) error {
	if swag.IsZero(m.WorkerGroup) { // not required
		return nil
	}

	if m.WorkerGroup != nil {
		if err := m.WorkerGroup.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("workerGroup")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this worker model based on the context it is used
func (m *WorkerModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateWorkerGroup(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WorkerModel) contextValidateWorkerGroup(ctx context.Context, formats strfmt.Registry) error {

	if m.WorkerGroup != nil {
		if err := m.WorkerGroup.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("workerGroup")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WorkerModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WorkerModel) UnmarshalBinary(b []byte) error {
	var res WorkerModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
