// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Worker worker
//
// swagger:model Worker
type Worker struct {

	// h r
	HR string `json:"HR,omitempty"`

	// last beat
	LastBeat string `json:"LastBeat,omitempty"`

	// name
	Name string `json:"Name,omitempty"`
}

// Validate validates this worker
func (m *Worker) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this worker based on context it is used
func (m *Worker) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Worker) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Worker) UnmarshalBinary(b []byte) error {
	var res Worker
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
